### ISSUE TITLE
При копирование директории не сохраняется в указанную в route

### ISSUE THREAD

**Issue by Vanekru** [powerdot/easy-yandex-s3#1]
Мне кажется вот тут опечатка, надо поменять местами. `path.resolve(file.relative_dir_path, route)`

https://github.com/powerdot/easy-yandex-s3/blob/cd3aeb31c247275fab381eadb710a8ca42cb6969/index.js#L188

Спасибо за работу :)

**Comment by powerdot** [comment]
Привет!
Слушай, не уверен, что в этом ошибка, ведь сначала нужен роут, куда загружаем:
допустим загружаем в ./serverFiles/
И потом он берет относительный путь, допустим файла /files/file.pdf
и у него должно получится в бакете следующее: ./serverFiles/ + /files/file.pdf 

Подскажи, ты пробовал исправить эту строчку? Получилось?)
Или покажи отрывок кода как ты используешь загрузку директории в бакет:)

**Comment by Vanekru** [comment]
Да я у себя исправил и работает. Гружу вот так
```
var upload = s3.Upload({
        path: "./" + folder,
        save_name: true,
      }, "/" + folder + "/");
```

**Comment by simbik** [comment]
Подтверждаю не работает!
Путь резолвится неверно, там должен быть не path.resolve, а path.join. (Так как мы же должны указать папку на бакете + он берет relative путь файла).

**Comment by powerdot** [comment]
Господа, зарелизил с path.join'ом
