### ISSUE TITLE
Indentation, code style

### ISSUE THREAD

**Issue by nukuutos** [powerdot/easy-yandex-s3#14]
@powerdot 

Как насчёт того, чтобы привести код в репозитории к одному виду? Например, отступы в проекте: они либо табуляцией, либо в 4 пробела. Обычно используется 2 пробела или 4 пробела. Я сам склонен к двум пробелам.

При этом как насчёт того, чтобы добавить prettier + eslint?
Если да, то какого код-стайла придерживаеться: airbnb, standart, google, ... ? Я предлагаю airbnb

**Comment by powerdot** [comment]
@nukuutos 
Никита, ты просто класс
Правда у меня сейчас не очень много времени её дорабатывать, давай я тебя заинвайчу в коллаб, чтобы это была и твоя библиотека, вноси полезности на вкус<3

**Comment by nukuutos** [comment]
Вау, я очень ценю это!😍
Но обсуждения я буду всё равно открывать и звать тебя, если будет что-то спорное/непонятное или в каком-то смысле глобальное🤗😄
