### ISSUE TITLE
Прямой upload через express возможно?

### ISSUE THREAD

**Issue by dalisoft** [powerdot/easy-yandex-s3#2]
Здорова!

а можно ли прямо из express выгружать на Yandex Object Storage? Было бы здорово

**Comment by powerdot** [comment]
Йо! Привет!
Ты имеешь в виду шобы на веб-форму загнать файл, отправить на сервер и чтобы серчер сам его загрузил на Яндекс?

**Comment by dalisoft** [comment]
Да, вро

**Comment by dalisoft** [comment]
(Случайно нажал на закрыть исю, сорян)

**Comment by powerdot** [comment]
Смотри, я решал это так:
Добавляем multer как мидлвар для понимания загрузок файлов и
```js
router.post('/uploadFile', async(req,res)=>{
    var upload = await s3.Upload({buffer: req.files[0].buffer}, '/files/');
    res.send(upload);
});
```

**Comment by dalisoft** [comment]
Спасибо, попробую.
