### ISSUE TITLE
ОС Windows 10 битые пути загрузки в облако

### ISSUE THREAD

**Issue by simbik** [powerdot/easy-yandex-s3#6]
На windows 10 при загрузке пути на облако битые (вида key: '\\media\\sampleVideo\\/1080p_001.ts'), соответственно грузит не в папки, а создает новую папку с таким вот кривым именем.

**Comment by nukuutos** [comment]
Исправлено в этом коммите 9a5dd51b54d5a751bc2a6b1d673f56fa22f36013. В ближайшем релизе будет содержаться фикс.
